// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: myprotobuf/tmp.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Detail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age     int64  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Detail) Reset() {
	*x = Detail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myprotobuf_tmp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_myprotobuf_tmp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_myprotobuf_tmp_proto_rawDescGZIP(), []int{0}
}

func (x *Detail) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Detail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Detail) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_myprotobuf_tmp_proto protoreflect.FileDescriptor

var file_myprotobuf_tmp_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x48, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myprotobuf_tmp_proto_rawDescOnce sync.Once
	file_myprotobuf_tmp_proto_rawDescData = file_myprotobuf_tmp_proto_rawDesc
)

func file_myprotobuf_tmp_proto_rawDescGZIP() []byte {
	file_myprotobuf_tmp_proto_rawDescOnce.Do(func() {
		file_myprotobuf_tmp_proto_rawDescData = protoimpl.X.CompressGZIP(file_myprotobuf_tmp_proto_rawDescData)
	})
	return file_myprotobuf_tmp_proto_rawDescData
}

var file_myprotobuf_tmp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_myprotobuf_tmp_proto_goTypes = []interface{}{
	(*Detail)(nil), // 0: myprotobuf.Detail
}
var file_myprotobuf_tmp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_myprotobuf_tmp_proto_init() }
func file_myprotobuf_tmp_proto_init() {
	if File_myprotobuf_tmp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myprotobuf_tmp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Detail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myprotobuf_tmp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_myprotobuf_tmp_proto_goTypes,
		DependencyIndexes: file_myprotobuf_tmp_proto_depIdxs,
		MessageInfos:      file_myprotobuf_tmp_proto_msgTypes,
	}.Build()
	File_myprotobuf_tmp_proto = out.File
	file_myprotobuf_tmp_proto_rawDesc = nil
	file_myprotobuf_tmp_proto_goTypes = nil
	file_myprotobuf_tmp_proto_depIdxs = nil
}
